CRUDWITHUOWPT1/Controllers/CourseController.cs
using CRUDSEPARATIONOFCONCENTP1.BusinessLogic;
using CRUDSEPARATIONOFCONCENTP1.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUDWITHUOWPT1.Controllers
{
    public class CourseController : Controller
    {

        CourseBusinessLogic course = new CourseBusinessLogic();
        // GET: Call the method that returns all courses
        // Search: returns all courses matching specified search term
        public ActionResult Index(string name, int? page, string SortOrder)
        {
            ViewBag.SortByCourseName = SortOrder == "CourseName" ? "Course_Descending" : "CourseName";
            ViewBag.SortByDate = SortOrder == "Date" ? "Date_Descending" : "Date";


            if (name == null)
            {
                var getcourse = from i in course.GetAllCourses()
                                select i;
                switch (SortOrder)
                {
                    case "Course_Descending":
                        getcourse = getcourse.OrderByDescending(x => x.CourseName).ToList();
                        break;
                    case "CourseName":
                        getcourse = getcourse.OrderBy(x => x.CourseName).ToList();
                        break;
                    case "Date_Descending":
                        getcourse = getcourse.OrderByDescending(x => x.DateCreated).ToList();
                        break;
                    case "Date":
                        getcourse = getcourse.OrderBy(x => x.DateCreated).ToList();
                        break;
                    default:
                        getcourse = getcourse.OrderBy(x => x.CourseName).ToList();
                        break;

                }

                int pagesize = 5;
                int pagenumber = (page ?? 1);

                return View(getcourse.ToPagedList(pagenumber, pagesize));
            }
            else
            {
                var getcoursebysearch = from i in course.SearchCourse(name)
                                        select i;
                switch (SortOrder)
                {
                    case "Course_Descending":
                        getcoursebysearch = getcoursebysearch.OrderByDescending(x => x.CourseName).ToList();
                        break;
                    case "CourseName":
                        getcoursebysearch = getcoursebysearch.OrderBy(x => x.CourseName).ToList();
                        break;
                    case "Date_Descending":
                        getcoursebysearch = getcoursebysearch.OrderByDescending(x => x.DateCreated).ToList();
                        break;
                    case "Date":
                        getcoursebysearch = getcoursebysearch.OrderBy(x => x.DateCreated).ToList();
                        break;
                    default:
                        getcoursebysearch = getcoursebysearch.OrderBy(x => x.CourseName).ToList();
                        break;
                }

                int pagesize = 5;
                int pagenumber = (page ?? 1);

                return View(getcoursebysearch.ToPagedList(pagenumber, pagesize));
            }
        }

        [HttpPost]
        public JsonResult SearchJson(string name)
        {
            var get = course.SearchCourse(name);

            return Json(get, JsonRequestBehavior.AllowGet);
        }


        // GET: Course/Details/5
        //// Calls the method from business logic that returns details for each record from the database based on the record id
        //public ActionResult Details(int id)
        //{
        //    if (id != 0)
        //    {
        //        GetCourseByIdViewModel model = course.GetById(id);

        //        return PartialView("_Details", model);
        //    }
        //    return RedirectToAction("Index");
        //}

        // GET: Course/Create
        // return the create view
        public ActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        // Call the method from business logic that adds a record onto database
        [HttpPost]
        public ActionResult Create(CreateCourseViewModel model)
        {
            model.DateCreated = DateTime.Now;
            if (ModelState.IsValid)
            {
                course.AddCourse(model);
                return RedirectToAction("Create","Student");
            }
            return View(model);
        }

        // GET: Course/Edit/5
        // Call the method from business logic to return the record based on the id
        //public ActionResult Edit(int id)
        //{
        //    GetCourseByIdViewModel model = course.GetById(id);
        //    return PartialView("_Update",model);
        //}

        //// POST: Course/Edit/5
        //// Call the update method from business logic and post the view 
        //[HttpPost]
        //public ActionResult Edit(int id, GetCourseByIdViewModel model)
        //{
        //    if (id != 0)
        //    {
        //        course.UpdateCourse(id, model);
        //        return RedirectToAction("Index");
        //    }
        //    return RedirectToAction("Index");
        //}

        // Call the delete method from business logic to remove the record based on the record id
        public ActionResult Delete(int id)
        {
            if (id != 0)
            {
                course.GetById(id);
                course.DeleteCourse(id);

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

CRUDWITHUOWPT1/Controllers/StudentController.cs
using CRUDSEPARATIONOFCONCENTP1.BusinessLogic;
using CRUDSEPARATIONOFCONCENTP1.ViewModels;
using CRUDWITHUOWPT1.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUDWITHUOWPT1.Controllers
{

    public class StudentController : Controller
    {
        StudentBusinessLogic student = new StudentBusinessLogic();
        CourseBusinessLogic course = new CourseBusinessLogic();
        // GET: Calls the method from business logic to return all the records
        // Pass the stirng variable to search method from the business logic to return record(s) base on it.
        public ActionResult Index(string name, int? page, string SortOrder)
        {
            ViewBag.CourseName = SortOrder == "CourseName" ? "Course_Descending" : "CourseName";
            ViewBag.StudentName = SortOrder == "StudentName" ? "Student_Descending" : "StudentName";
            ViewBag.StudentSurname = SortOrder == "StudentSurname" ? "Surname_Descending" : "StudentSurname";
            ViewBag.StudentNumber = SortOrder == "StudentNumber" ? "Number_Descending" : "StudentNumber";

            var studentget = from i in student.GetAllByCondition()
                             select i;
            var studentsearched = from s in student.SearchByName(name)
                                  select s;

            if (name == null)
            {

                int pagesize = 5;
                int pagenumber = (page ?? 1);

                switch (SortOrder)
                {
                    case "Course_Descending":
                        studentget = studentget.OrderByDescending(x => x.CourseName).ToList();
                        break;
                    case "CourseName":
                        studentget = studentget.OrderBy(x => x.CourseName).ToList();
                        break;
                    case "Student_Descending":
                        studentget = studentget.OrderByDescending(x => x.Name).ToList();
                        break;
                    case "StudentName":
                        studentget = studentget.OrderBy(x => x.Name).ToList();
                        break;
                    case "Surname_Descending":
                        studentget = studentget.OrderByDescending(x => x.Surname).ToList();
                        break;
                    case "StudentSurname":
                        studentget = studentget.OrderBy(x => x.Surname).ToList();
                        break;
                    case "Number_Descending":
                        studentget = studentget.OrderByDescending(x => x.StudentNumber).ToList();
                        break;
                    case "StudentNumber":
                        studentget = studentget.OrderBy(x => x.StudentNumber).ToList();
                        break;
                    default:
                        studentget = studentget.OrderBy(x => x.Name).ToList();
                        break;
                }
                return View(studentget.ToPagedList(pagenumber, pagesize));
            }

            else if (name != null)
            {
                int pagesize = 5;
                int pagenumber = (page ?? 1);

                switch (SortOrder)
                {
                    case "Course_Descending":
                        studentsearched = studentsearched.OrderByDescending(x => x.CourseName).ToList();
                        break;
                    case "CourseName":
                        studentsearched = studentsearched.OrderBy(x => x.CourseName).ToList();
                        break;
                    case "Student_Descending":
                        studentsearched = studentsearched.OrderByDescending(x => x.Name).ToList();
                        break;
                    case "StudentName":
                        studentsearched = studentsearched.OrderBy(x => x.Name).ToList();
                        break;
                    case "Surname_Descending":
                        studentsearched = studentsearched.OrderByDescending(x => x.Surname).ToList();
                        break;
                    case "StudentSurname":
                        studentsearched = studentsearched.OrderBy(x => x.Surname).ToList();
                        break;
                    case "Number_Descending":
                        studentsearched = studentsearched.OrderByDescending(x => x.StudentNumber).ToList();
                        break;
                    case "StudentNumber":
                        studentsearched = studentsearched.OrderBy(x => x.StudentNumber).ToList();
                        break;
                    default:
                        studentsearched = studentsearched.OrderBy(x => x.Name).ToList();
                        break;
                }
                return View(studentsearched.ToPagedList(pagenumber,pagesize));
            }
            return RedirectToAction("Index");
        }

        // GET: Student/Details/5
        // Call the getby id method from business logic to return the record matching the id
        //public ActionResult Details(int id)
        //{
        //    if (id != 0)
        //    {
        //        GetByIdViewModel model = student.GetByStudentId(id);
        //        return PartialView("_Details",model);
        //    }
        //    return RedirectToAction("Index");
        //}

        // GET: Student/Create
        // Returns the create view 
        public ActionResult Create()
        {
            var course = new CourseBusinessLogic();
            ViewBag.StudentCourseId = new SelectList(course.GetAllCourses(), "CourseId", "CourseName", "Please Select");

            return View();
        }

        // POST: Student/Create
        // Calls the method from the business logic to add onto database
        [HttpPost]
        public ActionResult Create(CourseStudentViewModel model)
        {
            model.Student.DateCreated = DateTime.Now;
            
            if (ModelState.IsValid)
            {
                student.AddStudent(model.Student);
                return RedirectToAction("Index");
            }
            ViewBag.StudentCourseId = new SelectList(course.GetAllCourses(), "CourseId", "CourseName", "Please Select");
            return View(model);
        }

      
        // GET: Student/Edit/5
        //returns the view for the update
        //public ActionResult Edit(int id)
        //{
        //    if (id != 0)
        //    {
        //        GetByIdViewModel model = student.GetByStudentId(id);
        //        var course = new CourseBusinessLogic();
        //        ViewBag.CourseId = new SelectList(course.GetAllCourses(), "CourseId", "CourseName");
        //        return PartialView("_Update", model);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index");
        //    }

        //}

        // POST: Student/Edit/5
        // Calls the method from the business logic to update a record based on the id
        //[HttpPost]
        //public ActionResult Edit(int id, GetByIdViewModel model)
        //{
        //    if (id == 0)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    //Calling the get method from the student business logic
        //    else
        //    {
        //        student.GetByStudentId(id);
        //        student.UpdateStudent(id, model);
        //        var course = new CourseBusinessLogic();
        //        ViewBag.CourseId = new SelectList(course.GetAllCourses(), "CourseId", "CourseName");
        //        return RedirectToAction("Index");

        //    }

        //}
        // Calls the deelete method from the business logic to remove the record based on the specified record
        public ActionResult Delete(int id)
        {
            if (id != 0)
            {
                student.GetById(id);

                student.RemoveStudent(id);

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");

        }
    }
}

CRUDWITHUOWPT1/Views/Student/Create.cshtml
@model CRUDWITHUOWPT1.ViewModels.CourseStudentViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
   
    <div class="modal-header">
       
        <button type="button" id="btnShowModal" class="btn btn-info btn-lg" data-toggle="modal">Create Course</button>
    </div>

    <div class="panel panel-success">
        <!-- Default panel contents -->
        <div class="panel-heading">Add Student</div>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Student.CourseId  , htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("StudentCourseId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Student.CourseId, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Student.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Student.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Student.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Student.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Student.Surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Student.Surname, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.StudentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StudentNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>

    
    

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Course</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Course.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Course.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Course.CourseName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-2">

                    </div>
                    <div class="col-lg-4">
                        <input type="Submit" id="btnsave" value="Create" class="btn btn-success" />
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                   
                </div>
            </div>

        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">

       
            $("#btnShowModal").click(function () {
                $("#myModal").modal('show');
            });

            $("#btnHideModal").click(function () {
                $("#myModal").modal('hide');
            });
      

        $("#btnsave").click(function () {
            var url = '@Url.Action("Create", "Course")';
            $.ajax({
                type: 'POST',
                url: url,
                dataType: 'json',
                success: function (states) {

                },
                error: function (ex) {
                    alert();
                }
            });
        });
    </script>  
    }

CRUDWITHUOWPT1/Views/Student/Details.cshtml
@model CRUDSEPARATIONOFCONCENTP1.ViewModels.GetByIdViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CRUDWITHUOWPT1/Views/Student/Edit.cshtml
@model CRUDSEPARATIONOFCONCENTP1.ViewModels.GetByIdViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>

</p>

<div class="panel panel-success">
    <!-- Default panel contents -->
    <div class="panel-heading">Update Student Information</div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.StudentId)

            <div class="form-group">
                @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StudentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StudentNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-info" />
                </div>
            </div>
        </div>
    }
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }